server:
  port: 8081
  servlet:
    context-path: /api-yourcar/



spring:
  application:
    name: yourcar
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB

  main:
    allow-circular-references: false

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:mysql://localhost:3306/yourcar_test?createDatabaseIfNotExist=true
    username: root
    password: admin1
    driver-class-name: com.mysql.cj.jdbc.Driver


rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem